### ISSUE TITLE
calibrate 

### ISSUE THREAD

**Issue by tonyvr4** [wollewald/ADXL345_WE#2]
How can I calibrate the ADXL345.  It seems that the numbers do not want to settle to zero even if the module is taped to a desk

**Comment by wollewald** [comment]
I have only implemented a method to ensure to get a min/max of -1g/+1g for each axis. For this the min/max values for the axes are used (only gravity). The min/max raw values I obtained for one module for x,y,z were for example: -266/+285, -268/+278, -291/214. Ideally that should be symmetrical. I have made the asssumption that the zero point (when the sensor for the axis is at 0°) is in the middle: (min + max)/2. This may be true, but it could also be that the zero degrees is really where the sensor measures 0 and the slope is different from 0 to 90 and 0 to -90. What is really true I don't know. I have not fod this information.

I assume you would like to have 0g for x and y and 1g for z when the sensor is positioned flat. Of course I could set offsets for this starting position and in fact I did this for measuring (small) angles (see example sketch). But with this method you not necessarily get -/+1g for -/+90°C. I hope you can still follow my thoughts. At the end I did not find the one method which really ensures correct calibration in order to have the right starting values 0/0/1g and the right slope. That's why I have not implemented it.

**Comment by wollewald** [comment]
Since there was no further discussion I close this issue.
