### ISSUE TITLE
Arduino IDE 2.0.0-rc3 - Error 13 while installing using the library manage

### ISSUE THREAD

**Issue by vipulpurohit** [wollewald/ADXL345_WE#5]
Hello,
I'm trying to install this library using the Arduino IDE v2.0.0-rc3 using the in-built library manager but the installation failed with the following error message:

```
Downloading ADXL345_WE@2.1.2
Installing ADXL345_WE@2.1.2
Failed to install library: ADXL345_WE:2.1.2.
Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: rename C:\Users\Admin\Documents\Arduino\libraries\package-469848640\ADXL345_WE-2.1.2 C:\Users\Admin\Documents\Arduino\libraries\ADXL345_WE: Access is denied.
```

I tried launching the IDE with admin rights but still getting the same issue.

Thanks

**Comment by wollewald** [comment]
Hi @vipulpurohit,

to test this I have just deleted the library on my computer and re-installed it using the library manager. I also used the Arduino IDE 2.0.0-rc3. On my computer (Windows 11) it worked without any issues.

![Screenshot 2022-02-08 145914](https://user-images.githubusercontent.com/41305162/153022493-d6b094cb-a2e6-46f6-b3fa-898dd114ba5a.png)

This leads us to the difficult question why it doesn't work on your computer. Trying it with admin rights was a good idea. What happens if you install other libraries? Can you install them without problems? If this works then please give me an example and I can have a look if I see any obvious difference. If you have not yet tried other libraries can you do so? Just take any library.  If this works then please tell me which one you have installed and I can check if there's any obvious difference. You could then also try to install any other library from me (e.g. MCP23017_WE) to see if there's any systematic issue with my libs on your computer.

**Comment by vipulpurohit** [comment]
Hello @wollewald 
Sorry for the delayed response. Please find the answerer below:

Q: What happens if you install other libraries? Can you install them without problems?
A: I'm able to install other libraries without any issues. I tried Adafruit and a few other libraries.
```
SparkFun_ADXL345: https://github.com/sparkfun/SparkFun_ADXL345_Arduino_Library 
Adafruit ADXL345: https://github.com/adafruit/Adafruit_ADXL345
Seeed-Studio 345: https://github.com/Seeed-Studio/Accelerometer_ADXL345
```

Unfortunately again I'm not able to install your MCP23017_WE library and getting the following error:
```
Downloading MCP23017_WE@1.4.1
Installing MCP23017_WE@1.4.1
Failed to install the library: MCP23017_WE:1.4.1.
Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: rename C:\Users\Admin\Documents\Arduino\libraries\package-801393706\MCP23017_WE-1.4.1 C:\Users\Admin\Documents\Arduino\libraries\MCP23017_WE: Access is denied.
```

I'm using the following build of Arduino:
```
Version: 2.0.0-rc3
Date: 2021-12-22T15:46:56.004Z
CLI Version: 0.20.2 [13783819]
```
in Windows 10 Home Single

Let me know if you need further information on this issue.
Thanks.

**Comment by wollewald** [comment]
Hi @vipulpurohit , very strange. I had short look and don't see differences betwwen the libs ayou can install and mine. The problem is that can't reproduce the issue. On my system all works fine. If should find the problem I will tell you, but currently I am not not very optimistic. 
Does manual installation work (downlad the lib as zip and extract it to the Arduino library folder)? 
No other idea for the moment.

**Comment by vipulpurohit** [comment]
Hello @wollewald 
Yes. Manual installation does work and I'm able to use the library.

Thanks for your investigation and efforts.

**Comment by wollewald** [comment]
Thanks - strange. A solution, but not satisfying, of course. Difficult for me to find a solution as I don't have this problem. My hope is that it is an issue on the Arduino IDE side which will be solved with future versions. By now I haven't heard that other people have the same issue. Let's see.

**Comment by wollewald** [comment]
Since ther was no further comment and since I haven't heard of any similar issue, I am closing this issue.
